### ISSUE TITLE
Duplicate words in dictionaries

### ISSUE THREAD

**Issue by aagorchakov** [huseyn0w/Vocabularify#1]
Dictionaries contain duplicate words, for example "der Schluss", "der Schlüssel", etc.
https://github.com/huseyn0w/Vocabularify/blob/main/languages/de/ru/a1.json#L522
https://github.com/huseyn0w/Vocabularify/blob/main/languages/de/ru/a1.json#L1009

**Comment by huseyn0w** [comment]
Hi @aagorchakov, thanks for message. I just released new version with bugfix and lots of new features:
https://github.com/huseyn0w/Vocabularify/releases/tag/2.0.0

Please let me know what you think
